version: '3'
services:
  node_container:
    container_name: topsection-server
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on: 
      - sql_container
    environment:
      - PORT=3000
  sql_container:
    container_name: db-docker_mysql-development_1
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: anrMar#18
      MYSQL_DATABASE: hello_world
      MYSQL_USER: root
      MYSQL_PASSWORD: anrMar#18
      MYSQL_HOST: localhost
    ports:
      - "3308:3306"
    expose:
      - 3306